# Generated by Django 3.2.4 on 2021-07-02 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('descripcion', models.CharField(default='', max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('stock', models.BooleanField(default=False)),
                ('fecha', models.DateField(verbose_name='fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=70)),
                ('segundo_n', models.CharField(default='', max_length=70)),
                ('apellido_p', models.CharField(default='', max_length=70)),
                ('apellido_m', models.CharField(default='', max_length=70)),
                ('direccion', models.CharField(default='', max_length=70)),
                ('casa_dpto', models.CharField(default='', max_length=70)),
                ('nro_casa', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('nro_telefono', models.CharField(default='', max_length=70)),
                ('pago', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakehouse.producto')),
            ],
        ),
    ]
