# Generated by Django 3.2.3 on 2021-07-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'permissions': (('gerente', 'Gerente cakehouse'),)},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('gerente', 'Gerente cakehouse'),)},
        ),
    ]
