# Generated by Django 3.2.4 on 2021-07-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakehouse', '0002_auto_20210704_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
